# Group by and Aggregate Functions

Simple exercise based on [https://github.com/AlexTheAnalyst/PandasYouTubeSeries](https://github.com/AlexTheAnalyst/PandasYouTubeSeries)

*Visualisation Tip*
If you prefer the Jupyter Notebook render over VS Code's data wrangler, you can disable the `data wrangler output viewer` option in the settings. 
See [https://jopx.blogspot.com/2025/12/enable-and-disable-data-wranger-in-vs.html](https://jopx.blogspot.com/2025/12/enable-and-disable-data-wranger-in-vs.html) for more details.

In [1]:
## As always, import pandas as ...

import pandas as pd

In [2]:
## Read CSV from GitHub url: https://github.com/AlexTheAnalyst/PandasYouTubeSeries/blob/main/Flavors.csv?raw=true

flavors = pd.read_csv("https://github.com/AlexTheAnalyst/PandasYouTubeSeries/blob/main/Flavors.csv?raw=true")
flavors

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [3]:
## Explore the data

flavors.head(5)
flavors.shape
flavors.info()
flavors.describe()
## Success? Commit changes to the repository!

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Flavor          9 non-null      str
 1   Base Flavor     9 non-null      str
 2   Liked           9 non-null      str
 3   Flavor Rating   9 non-null      float64
 4   Texture Rating  9 non-null      float64
 5   Total Rating    9 non-null      float64
dtypes: float64(3), str(3)
memory usage: 564.0 bytes

       Flavor Rating  Texture Rating  Total Rating
count         9.0000        9.000000      9.000000
mean          6.6000        6.177778     12.800000
std           2.5387        1.478832      4.030509
min           2.3000        3.400000      5.700000
25%           4.7000        5.000000      9.700000
50%           6.9000        6.500000     13.400000
75%           8.2000        7.100000     15.300000
max          10.0000        8.000000     18.000000

In [4]:
## Let's group by Base Flavor

flavors['Base Flavor']
flavors['Base Flavor'].count()
flavors['Base Flavor'].value_counts()
flavors.groupby('Base Flavor')['Total Rating'].mean()
flavors.groupby('Base Flavor').mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [5]:
## Make this a new datafram

group_flavors = flavors.groupby('Base Flavor')

# Calculated the means of the new (Grouped) dataframe. Used the numveric_only argument to make sure that non-numerical values are excluded from calculation.

## Success? Commit changes to the repository!

In [6]:
## Let's count the number of flavors for each Base Flavor
group_flavors.size()

Base Flavor
Chocolate    3
Vanilla      6
dtype: int64

In [7]:
## Let's get the means for each Base Flavor

group_flavors.mean(numeric_only=True)

## Success? Commit changes to the repository!

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [ ]:
## Let's try that in one line

In [8]:
## Let's discover some popular aggregate statistics like count, sum, min, max. Notice that text columns will appear with min and max as well

group_flavors.min(numeric_only=True)
group_flavors.max(numeric_only=True)
group_flavors.sum(numeric_only=True)
group_flavors.count()

## Success? Commit changes to the repository!

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [9]:
flavors.columns

Index(['Flavor', 'Base Flavor', 'Liked', 'Flavor Rating', 'Texture Rating',
       'Total Rating'],
      dtype='str')

In [10]:
## Let's try more advanced aggregation with the `agg` function
## We have to specify which columns we want to aggregate and which functions to apply to them via a dictionary
# group_flavors['Total Rating'].agg({'mean', 'sum','max','min'})

agg_dictionary = {
    "Flavor Rating" : ['mean', 'sum', 'max', 'min'],
    "Texture Rating" : ['mean', 'sum', 'max', 'min']
}

group_flavors.agg(agg_dictionary)
## Success? Commit changes to the repository!

            Flavor Rating                  Texture Rating
                     mean   sum   max  min           mean   sum  max  min
Base Flavor
Chocolate             8.4  25.2   8.8  8.2       7.233333  21.7  7.6  7.0
Vanilla               5.7  34.2  10.0  2.3       5.650000  33.9  8.0  3.4

In [11]:
flavors

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [12]:
## Let's group on multiple columns
## Check the dataframe again and group by Base Flavor and Liked (and show mean as value)
# Per Base Flavor, what is the average Flavor Rating among Liked 'yes' 'no'

flavors.groupby(['Base Flavor','Liked']).mean(numeric_only=True)

# Grouped the original dataframe(flavors) by Base Flavor and Liked. Then, calculated the mean. Got an error,
# Because of strings. Then, added the numeric_only = True argument

                   Flavor Rating  Texture Rating  Total Rating
Base Flavor Liked
Chocolate   Yes              8.4        7.233333     15.700000
Vanilla     No               3.6        4.466667      8.066667
            Yes              7.8        6.833333     14.633333

In [ ]:
# Do the multiple aggregation for Base Flavor and Liked

group_by_FR_Liked = flavors.groupby(['Base Flavor','Liked'])
group_by_FR_Liked.agg(agg_dictionary)

## Question from student : Does it matter (for this example) if you change the order of Goupby Columns 
## Answer : compare the table above and below

                  Flavor Rating                  Texture Rating             \
                           mean   sum   max  min           mean   sum  max
Base Flavor Liked
Chocolate   Yes             8.4  25.2   8.8  8.2       7.233333  21.7  7.6
Vanilla     No              3.6  10.8   4.7  2.3       4.466667  13.4  5.0
            Yes             7.8  23.4  10.0  6.5       6.833333  20.5  8.0


                   min
Base Flavor Liked
Chocolate   Yes    7.0
Vanilla     No     3.4
            Yes    6.0

In [ ]:
## Success? Commit changes to the repository!

In [ ]:
## Let's disover an easier way to analyze the grouped data quickly

In [ ]:
## Success? Commit changes and push the repository to GitHub!